config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://https://github.com/mleisa/argocd-example-argocd
      targetRevision: master

applications:
  - name: guestbook-argocd
