config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/argoproj/argocd-example-apps
      targetRevision: master

applications:
  - name: guestbook-argocd
  - name: helm-hooks
  - name: jsonnet-guestbook
  - name: jsonnet-guestbook-tla
  - name: kustomize-guestbook
  - name: pre-post-sync
  - name: sock-shop
  - name: sync-waves
